export { default as register } from './register/register';
export { default as login } from './login/login';
export { default as emailVerification } from './emailVerification/emailVerification';
export { default as forgotPassword } from './forgotPassword/forgotPassword';
export { default as logout } from './logout/logout';
export { default as resetPassword } from './resetPassword/resetPassword';
export { default as refreshToken } from './refreshToken/refreshToken';
export { default as googleOAuth } from './googleAuth/googleAuth';
export { default as me } from './me/me';
